### ISSUE TITLE
Feature request: adding tags to EBS volumes

### ISSUE THREAD

**Issue by yambottle** [NextChapterSoftware/ec2-action-builder#21]
Made a [PR](https://github.com/NextChapterSoftware/ec2-action-builder/pull/20)

**Comment by mahdi-torabi** [comment]
Tested this change and works fine. Waiting to wrap up another [issue](https://github.com/NextChapterSoftware/ec2-action-builder/issues/22) so we could push a release for both

**Comment by mahdi-torabi** [comment]
Merged the PR https://github.com/NextChapterSoftware/ec2-action-builder/pull/23

Released V1.6 with the EBS tagging fix.
