### ISSUE TITLE
Can const retryIntervalSeconds = 10; be customized?

### ISSUE THREAD

**Issue by brianbattformant** [NextChapterSoftware/ec2-action-builder#30]
Hi there!  I'm finding that I'm quickly running out of Github tokens using this action.  Is it possible to customize the retryIntervalSeconds in the yaml script?  Here's the instances where I'd like to customize it:

https://github.com/NextChapterSoftware/ec2-action-builder/blob/main/src/github/github.ts#L95

https://github.com/NextChapterSoftware/ec2-action-builder/blob/main/src/github/github.ts#L132

**Comment by mahdi-torabi** [comment]
Hmm, this basically makes 6 API requests/second and since it's an authenticated request it shouldn't cause an issue. 
I can make it configurable through the action settings. Would that work ?

**Comment by brianbattformant** [comment]
Hi there!  Yes, if you could make it configurable, that would be amazing.  Thanks you!

**Comment by mahdi-torabi** [comment]
https://github.com/NextChapterSoftware/ec2-action-builder/pull/33

Release 1.8 is out with this change

**Comment by brianbattformant** [comment]
We're no longer hitting github token limits.  Thank you for this!
